version: '3'
services:
  directus:
    image: directus/directus:latest
    ports:
      - "8055:8055"
    environment:
      DIRECTUS_ADMIN_EMAIL: "admin@example.com"
      DIRECTUS_ADMIN_PASSWORD: "password"
      DIRECTUS_KEY: "your-secret-key"
      DIRECTUS_SECRET: "your-secret-secret"
      DB_CLIENT: "sqlite"
      DB_FILENAME: "/directus/database/data.db"
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions