name: Test Multiple Linux VMs in GitHub CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-linux-vm:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        distro: [ubuntu, arch, fedora, centos, debian, alpine]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install QEMU and Dependencies
        run: |
          sudo apt update
          sudo apt install -y qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils genisoimage wget

      - name: Make Script Executable
        run: chmod +x scripts/test-linux.sh

      - name: Run ${{ matrix.distro }} VM and Execute Command
        run: scripts/test-linux.sh ${{ matrix.distro }} "bash <(curl -sSL https://install.doctor/start)"

      - name: Upload Logs for Debugging
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: vm-logs-${{ matrix.distro }}
          path: run-vm.log
