name: Run Bash Command on macOS CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-macos-command:
    runs-on: macos-latest  # Uses GitHub-hosted macOS runner
    timeout-minutes: 30

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Make Script Executable
        run: chmod +x scripts/test-macos.sh

      - name: Run Bash Script on macOS with Command
        run: scripts/test-macos.sh "echo 'bash <(curl -sSL https://install.doctor/start)'"

      - name: Upload Logs for Debugging
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: macos-script-logs
          path: macos-script.log